# ======= BUILD STAGE =======
FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# alpine lacks necessary dynamic libraries, so we build statically linked library
RUN CGO_ENABLED=0 GOOS=linux go build -o order-service ./cmd/app

# ======= FINAL STAGE =======
FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/order-service .

EXPOSE 50053

CMD ["./order-service"]
