// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: product_offer.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ProductId     int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SupplierId    int64                  `protobuf:"varint,5,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"` // user id of the supplier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductOfferRequest) Reset() {
	*x = CreateProductOfferRequest{}
	mi := &file_product_offer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductOfferRequest) ProtoMessage() {}

func (x *CreateProductOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_offer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductOfferRequest.ProtoReflect.Descriptor instead.
func (*CreateProductOfferRequest) Descriptor() ([]byte, []int) {
	return file_product_offer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductOfferRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductOfferRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductOfferRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateProductOfferRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateProductOfferRequest) GetSupplierId() int64 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

type CreateProductOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductOfferResponse) Reset() {
	*x = CreateProductOfferResponse{}
	mi := &file_product_offer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductOfferResponse) ProtoMessage() {}

func (x *CreateProductOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_offer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductOfferResponse.ProtoReflect.Descriptor instead.
func (*CreateProductOfferResponse) Descriptor() ([]byte, []int) {
	return file_product_offer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductOfferResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateProductOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductOfferRequest) Reset() {
	*x = UpdateProductOfferRequest{}
	mi := &file_product_offer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductOfferRequest) ProtoMessage() {}

func (x *UpdateProductOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_offer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductOfferRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductOfferRequest) Descriptor() ([]byte, []int) {
	return file_product_offer_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProductOfferRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductOfferRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductOfferRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateProductOfferRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateProductOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *ProductOffer          `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductOfferResponse) Reset() {
	*x = UpdateProductOfferResponse{}
	mi := &file_product_offer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductOfferResponse) ProtoMessage() {}

func (x *UpdateProductOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_offer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductOfferResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductOfferResponse) Descriptor() ([]byte, []int) {
	return file_product_offer_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductOfferResponse) GetOffer() *ProductOffer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type DeleteProductOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductOfferRequest) Reset() {
	*x = DeleteProductOfferRequest{}
	mi := &file_product_offer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductOfferRequest) ProtoMessage() {}

func (x *DeleteProductOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_offer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductOfferRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductOfferRequest) Descriptor() ([]byte, []int) {
	return file_product_offer_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProductOfferRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductOfferResponse) Reset() {
	*x = DeleteProductOfferResponse{}
	mi := &file_product_offer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductOfferResponse) ProtoMessage() {}

func (x *DeleteProductOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_offer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductOfferResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductOfferResponse) Descriptor() ([]byte, []int) {
	return file_product_offer_proto_rawDescGZIP(), []int{5}
}

type ProductOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ProductId     int64                  `protobuf:"varint,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SupplierId    int64                  `protobuf:"varint,6,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"` // user id of the supplier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductOffer) Reset() {
	*x = ProductOffer{}
	mi := &file_product_offer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductOffer) ProtoMessage() {}

func (x *ProductOffer) ProtoReflect() protoreflect.Message {
	mi := &file_product_offer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductOffer.ProtoReflect.Descriptor instead.
func (*ProductOffer) Descriptor() ([]byte, []int) {
	return file_product_offer_proto_rawDescGZIP(), []int{6}
}

func (x *ProductOffer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductOffer) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductOffer) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductOffer) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProductOffer) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductOffer) GetSupplierId() int64 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

type GetProductOffersByProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductOffersByProductRequest) Reset() {
	*x = GetProductOffersByProductRequest{}
	mi := &file_product_offer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductOffersByProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductOffersByProductRequest) ProtoMessage() {}

func (x *GetProductOffersByProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_offer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductOffersByProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductOffersByProductRequest) Descriptor() ([]byte, []int) {
	return file_product_offer_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductOffersByProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductOffersByProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*ProductOffer        `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductOffersByProductResponse) Reset() {
	*x = GetProductOffersByProductResponse{}
	mi := &file_product_offer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductOffersByProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductOffersByProductResponse) ProtoMessage() {}

func (x *GetProductOffersByProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_offer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductOffersByProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductOffersByProductResponse) Descriptor() ([]byte, []int) {
	return file_product_offer_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductOffersByProductResponse) GetOffers() []*ProductOffer {
	if x != nil {
		return x.Offers
	}
	return nil
}

type GetProductOffersBySupplierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierId    int64                  `protobuf:"varint,1,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductOffersBySupplierRequest) Reset() {
	*x = GetProductOffersBySupplierRequest{}
	mi := &file_product_offer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductOffersBySupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductOffersBySupplierRequest) ProtoMessage() {}

func (x *GetProductOffersBySupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_offer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductOffersBySupplierRequest.ProtoReflect.Descriptor instead.
func (*GetProductOffersBySupplierRequest) Descriptor() ([]byte, []int) {
	return file_product_offer_proto_rawDescGZIP(), []int{9}
}

func (x *GetProductOffersBySupplierRequest) GetSupplierId() int64 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

type GetProductOffersBySupplierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*ProductOffer        `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductOffersBySupplierResponse) Reset() {
	*x = GetProductOffersBySupplierResponse{}
	mi := &file_product_offer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductOffersBySupplierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductOffersBySupplierResponse) ProtoMessage() {}

func (x *GetProductOffersBySupplierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_offer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductOffersBySupplierResponse.ProtoReflect.Descriptor instead.
func (*GetProductOffersBySupplierResponse) Descriptor() ([]byte, []int) {
	return file_product_offer_proto_rawDescGZIP(), []int{10}
}

func (x *GetProductOffersBySupplierResponse) GetOffers() []*ProductOffer {
	if x != nil {
		return x.Offers
	}
	return nil
}

var File_product_offer_proto protoreflect.FileDescriptor

const file_product_offer_proto_rawDesc = "" +
	"\n" +
	"\x13product_offer.proto\x12\aproduct\"\xa4\x01\n" +
	"\x19CreateProductOfferRequest\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\x12\x1f\n" +
	"\vsupplier_id\x18\x05 \x01(\x03R\n" +
	"supplierId\",\n" +
	"\x1aCreateProductOfferResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"t\n" +
	"\x19UpdateProductOfferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x05R\x05stock\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"I\n" +
	"\x1aUpdateProductOfferResponse\x12+\n" +
	"\x05offer\x18\x01 \x01(\v2\x15.product.ProductOfferR\x05offer\"+\n" +
	"\x19DeleteProductOfferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1c\n" +
	"\x1aDeleteProductOfferResponse\"\xa7\x01\n" +
	"\fProductOffer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x05R\x05stock\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"product_id\x18\x05 \x01(\x03R\tproductId\x12\x1f\n" +
	"\vsupplier_id\x18\x06 \x01(\x03R\n" +
	"supplierId\"A\n" +
	" GetProductOffersByProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"R\n" +
	"!GetProductOffersByProductResponse\x12-\n" +
	"\x06offers\x18\x01 \x03(\v2\x15.product.ProductOfferR\x06offers\"D\n" +
	"!GetProductOffersBySupplierRequest\x12\x1f\n" +
	"\vsupplier_id\x18\x01 \x01(\x03R\n" +
	"supplierId\"S\n" +
	"\"GetProductOffersBySupplierResponse\x12-\n" +
	"\x06offers\x18\x01 \x03(\v2\x15.product.ProductOfferR\x06offers2\x9d\x04\n" +
	"\x13ProductOfferService\x12]\n" +
	"\x12CreateProductOffer\x12\".product.CreateProductOfferRequest\x1a#.product.CreateProductOfferResponse\x12]\n" +
	"\x12UpdateProductOffer\x12\".product.UpdateProductOfferRequest\x1a#.product.UpdateProductOfferResponse\x12]\n" +
	"\x12DeleteProductOffer\x12\".product.DeleteProductOfferRequest\x1a#.product.DeleteProductOfferResponse\x12r\n" +
	"\x19GetProductOffersByProduct\x12).product.GetProductOffersByProductRequest\x1a*.product.GetProductOffersByProductResponse\x12u\n" +
	"\x1aGetProductOffersBySupplier\x12*.product.GetProductOffersBySupplierRequest\x1a+.product.GetProductOffersBySupplierResponseBQZOgithub.com/alibekkenny/simple-marketplace/shared/proto/genproto/product;productb\x06proto3"

var (
	file_product_offer_proto_rawDescOnce sync.Once
	file_product_offer_proto_rawDescData []byte
)

func file_product_offer_proto_rawDescGZIP() []byte {
	file_product_offer_proto_rawDescOnce.Do(func() {
		file_product_offer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_offer_proto_rawDesc), len(file_product_offer_proto_rawDesc)))
	})
	return file_product_offer_proto_rawDescData
}

var file_product_offer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_product_offer_proto_goTypes = []any{
	(*CreateProductOfferRequest)(nil),          // 0: product.CreateProductOfferRequest
	(*CreateProductOfferResponse)(nil),         // 1: product.CreateProductOfferResponse
	(*UpdateProductOfferRequest)(nil),          // 2: product.UpdateProductOfferRequest
	(*UpdateProductOfferResponse)(nil),         // 3: product.UpdateProductOfferResponse
	(*DeleteProductOfferRequest)(nil),          // 4: product.DeleteProductOfferRequest
	(*DeleteProductOfferResponse)(nil),         // 5: product.DeleteProductOfferResponse
	(*ProductOffer)(nil),                       // 6: product.ProductOffer
	(*GetProductOffersByProductRequest)(nil),   // 7: product.GetProductOffersByProductRequest
	(*GetProductOffersByProductResponse)(nil),  // 8: product.GetProductOffersByProductResponse
	(*GetProductOffersBySupplierRequest)(nil),  // 9: product.GetProductOffersBySupplierRequest
	(*GetProductOffersBySupplierResponse)(nil), // 10: product.GetProductOffersBySupplierResponse
}
var file_product_offer_proto_depIdxs = []int32{
	6,  // 0: product.UpdateProductOfferResponse.offer:type_name -> product.ProductOffer
	6,  // 1: product.GetProductOffersByProductResponse.offers:type_name -> product.ProductOffer
	6,  // 2: product.GetProductOffersBySupplierResponse.offers:type_name -> product.ProductOffer
	0,  // 3: product.ProductOfferService.CreateProductOffer:input_type -> product.CreateProductOfferRequest
	2,  // 4: product.ProductOfferService.UpdateProductOffer:input_type -> product.UpdateProductOfferRequest
	4,  // 5: product.ProductOfferService.DeleteProductOffer:input_type -> product.DeleteProductOfferRequest
	7,  // 6: product.ProductOfferService.GetProductOffersByProduct:input_type -> product.GetProductOffersByProductRequest
	9,  // 7: product.ProductOfferService.GetProductOffersBySupplier:input_type -> product.GetProductOffersBySupplierRequest
	1,  // 8: product.ProductOfferService.CreateProductOffer:output_type -> product.CreateProductOfferResponse
	3,  // 9: product.ProductOfferService.UpdateProductOffer:output_type -> product.UpdateProductOfferResponse
	5,  // 10: product.ProductOfferService.DeleteProductOffer:output_type -> product.DeleteProductOfferResponse
	8,  // 11: product.ProductOfferService.GetProductOffersByProduct:output_type -> product.GetProductOffersByProductResponse
	10, // 12: product.ProductOfferService.GetProductOffersBySupplier:output_type -> product.GetProductOffersBySupplierResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_product_offer_proto_init() }
func file_product_offer_proto_init() {
	if File_product_offer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_offer_proto_rawDesc), len(file_product_offer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_offer_proto_goTypes,
		DependencyIndexes: file_product_offer_proto_depIdxs,
		MessageInfos:      file_product_offer_proto_msgTypes,
	}.Build()
	File_product_offer_proto = out.File
	file_product_offer_proto_goTypes = nil
	file_product_offer_proto_depIdxs = nil
}
